### ISSUE TITLE
Improve test coverage.

### ISSUE THREAD

**Issue by ownlifeful** [ownlifeful/Graph-Undirected-Hamiltonicity#1]
`Devel::Cover`'s `cover -test` command indicates that branch coverage is less that 100% for some tests. Create test cases to fully exercise the code.

**Comment by heinsdorf** [comment]
Is this an assignment? I’m busy right now.

**Comment by ownlifeful** [comment]
Oh no! Not an assignment. I was just testing github's issue tracking system.

Here are my feelings on the election:

  trump_won.png
https://drive.google.com/file/d/0B6bVs1FWHpfeWDZwODFUdjlCZEU/view?usp=drivesdk

**Comment by heinsdorf** [comment]
My biggest fear is that Trump may “privatize” Social Security. Or start a nuclear war. Or let Manhattan sink into the rising sea level. Or cause riots by trying to deport all the people who make life worth living in NYC. Or start killing off poor women who vote Democrat. Or…
For every complex problem, there’s a simple solution that’s Wrong.
