### ISSUE TITLE
Wrong perl version specification in Makefile.PL

### ISSUE THREAD

**Issue by eserte** [ownlifeful/Graph-Undirected-Hamiltonicity#7]
The Makefile.PL currently says
```
use 5.18;
```
which really translates to 5.180.0, a perl version which does not exist yet. If Makefile.PL is chosen for building, then it usually fails:
```
Perl v5.180.0 required (did you mean v5.18.0?)--this is only v5.32.1, stopped at Makefile.PL line 1.
```
Maybe it's easiest to remove the Makefile.PL completely, as Build.PL does not have this problem.

**Comment by ownlifeful** [comment]
Changed to:

`use 5.18.0;
`
which should solve the issue. GitHub CI says its working.
